---
# tasks file for cis_level1_host_benchmark

- name: CIS Level 1 Benchmark vSphere 7
  block:
    # 1.1 (L1) Ensure ESXi is properly patched

    - name: Assert valid acceptance_level configured
      ansible.builtin.assert:
        that: acceptance_level in ['partner','vmware_accepted','vmware_certified']
        fail_msg: "`acceptance_level` must be set to partner, vmware_accepted, or vmware_certified"

    - name: 1.2 (L1) Ensure the Image Profile VIB acceptance level is configured properly
      community.vmware.vmware_host_acceptance:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        acceptance_level: '{{ acceptance_level }}'
        state: present
      delegate_to: localhost

    # 1.3 (L1) Ensure no unauthorized kernel modules are loaded on the host

    - name: 2.1 (L1) Ensure NTP time synchronization is configured properly
      ansible.builtin.import_role:
        name: umich_vci.vmware_host_config.configure_ntp

    # 2.2 (L1) Ensure the ESXi host firewall is configured to restrict access to services running on the host

    - name: 2.3 (L1) Ensure Managed Object Browser (MOB) is disabled
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Config.HostAgent.plugins.solo.enableMob': false
      delegate_to: localhost

    - name: 2.5 (L1) Ensure SNMP is configured properly
      ansible.builtin.import_role:
        name: umich_vci.vmware_host_config.configure_snmp

    - name: 2.6 (L1) Ensure dvfilter API is not configured if not used
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Net.DVFilterBindIpAddress': '{{ dvfilter_bind_ip_address if dvfilter_required|bool else "" }}'
      delegate_to: localhost

    # 2.7 (L1) Ensure expired and revoked SSL certificates are removed from the ESXi server

    # 2.8 (L1) Ensure vSphere Authentication Proxy is used when adding hosts to Active Directory

    # 3.1 (L1) Ensure a centralized location is configured to collect ESXi host core dumps

    # 3.2 (L1) Ensure persistent logging is configured for all ESXi hosts

    # 3.3 (L1) Ensure remote logging is configured for ESXi hosts

    # 4.1 (L1) Ensure a non-root user account exists for local admin access

    # 4.2 (L1) Ensure passwords are required to be complex

    - name: 4.3 (L1) Ensure the maximum failed login attempts is set to 5
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Security.AccountLockFailures': 5
      delegate_to: localhost

    - name: 4.4 (L1) Ensure account lockout is set to 15 minutes
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Security.AccountUnlockTime': 900
      delegate_to: localhost

    - name: 4.5 (L1) Ensure previous 5 passwords are prohibited
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Security.PasswordHistory': 5
      delegate_to: localhost

    # 4.6 (L1) Ensure Active Directory is used for local user authentication

    - name: 4.7 (L1) Ensure only authorized users and groups belong to the esxAdminsGroup group
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'Config.HostAgent.plugins.hostsvc.esxAdminsGroup': '{{ esx_admins_group }}'
      delegate_to: localhost

    # 4.8 (L1) Ensure the Exception Users list is properly configured

    - name: 5.1 (L1) Ensure the DCUI timeout is set to 600 seconds or less
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'UserVars.DcuiTimeOut': 600
      delegate_to: localhost

    - name: 5.2 (L1) Ensure the ESXi shell is disabled
      community.vmware.vmware_host_service_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        service_name: TSM
        service_policy: off
        state: stop
      delegate_to: localhost

    - name: 5.3 (L1) Ensure SSH is disabled
      community.vmware.vmware_host_service_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        service_name: TSM-SSH
        service_policy: off
        state: stop
      delegate_to: localhost

    #5.4 (L1) Ensure CIM access is limited
    #vmware_local_user_facts?

    # 5.5 (L1) Ensure Normal Lockdown mode is enabled

    - name: 5.8 (L1) Ensure idle ESXi shell and SSH sessions time out after 300 seconds or less
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'ESXiShellInteractiveTimeOut': 300
      delegate_to: localhost

    - name: 5.9 (L1) Ensure the shell services timeout is set to 1 hour or less
      vmware_host_config_manager:
        hostname: '{{ vmware_host }}'
        esxi_hostname: '{{ inventory_hostname }}'
        username: '{{ vmware_user }}'
        password: '{{ vmware_password }}'
        options:
            'ESXiShellTimeOut': 3600
      delegate_to: localhost

    - name: 5.10 (L1) Ensure DCUI has a trusted users list for lockdown mode
      community.vmware.vmware_host_config_manager:
        hostname: '{{ vcenter_hostname }}'
        esxi_hostname: '{{ inventory_hostname }}'
        options:
            'DCUI.Access': '{{ dcui_access_list }}'
      delegate_to: localhost

    # 6.1 (L1) Ensure bidirectional CHAP authentication for iSCSI traffic is enabled

    # 6.3 (L1) Ensure storage area network (SAN) resources are segregated properly

    # 7.1 (L1) Ensure the vSwitch Forged Transmits policy is set to reject

    # 7.2 (L1) Ensure the vSwitch MAC Address Change policy is set to reject

    # 7.3 (L1) Ensure the vSwitch Promiscuous Mode policy is set to reject

    # 7.4 (L1) Ensure port groups are not configured to the value of the native VLAN

    # 7.5 (L1) Ensure port groups are not configured to VLAN values reserved by upstream physical switches

    # 7.6 (L1) Ensure port groups are not configured to VLAN 4095 and 0 except for Virtual Guest Tagging (VGT)

    # 7.7 (L1) Ensure Virtual Distributed Switch Netflow traffic is sent to an authorized collector

    # 7.8 (L1) Ensure port-level configuration overrides are disabled.

  when: (ansible_distribution_version is version_compare("7.0.0", ">=")) and (ansible_distribution_version is version_compare("8.0.0", "<"))
