---
# tasks file for configure_snmp
- name: Clear SNMP config
  community.vmware.vmware_host_snmp:
    # hostname: '{{ vmware_host }}'
    # esxi_hostname: '{{ inventory_hostname }}'
    # Presently, only direct connection to ESXi is supported
    hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
    state: reset
    #temporary until we get vCenter working
    validate_certs: false
  delegate_to: localhost
  when: not snmp_required|bool

- name: Configure SNMP
  community.vmware.vmware_host_snmp:
    # hostname: '{{ vmware_host }}'
    # esxi_hostname: '{{ inventory_hostname }}'
    # Presently, only direct connection to ESXi is supported
    hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
    state: '{{ "enabled" if snmp_required|bool else "disabled" }}'
    log_level: '{{ "warning" if snmp_required|bool else "" }}'
    community: '{{ snmp_community if snmp_required|bool else "" }}'
    #temporary unti we get vCenter working
    validate_certs: false
  delegate_to: localhost

- name: Allow SNMP through the firewall
  community.vmware.vmware_host_firewall_manager:
    hostname: '{{ vmware_host }}'
    esxi_hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
    rules:
      - name: snmp
        enabled: '{{ snmp_required }}'
        allowed_hosts:
          all_ip: True
  delegate_to: localhost
  when: snmp_required|bool
