---
# defaults file for migrate_management_to_dvswitch
vmware_host: "{{ lookup('env','VMWARE_HOST') }}"
vmware_user: "{{ lookup('env','VMWARE_USER') }}"
vmware_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
