---
# tasks file for start_temporary_ssh
- name: Get the current state of all services
  community.vmware.vmware_host_service_facts:
    hostname: '{{ vcenter_hostname }}'
    esxi_hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
  delegate_to: localhost
  register: host_service_facts

- name: Start Temporary SSH
  community.vmware.vmware_host_service_manager:
    hostname: '{{ vcenter_hostname }}'
    esxi_hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
    service_name: TSM-SSH
    state: start
  delegate_to: localhost
  when: not host_service_facts['host_service_facts'][inventory_hostname] | selectattr('key', 'equalto', 'TSM-SSH') | map(attribute='running') | list | first | bool
  notify: Stop Temporary SSH
